import os

MM_URL = os.getenv("MM_URL")
MM_TOKEN = os.getenv("MM_TOKEN")

QUEUE_FILE = "queue.json"

FIRST_REMINDER = 5 * 60
SECOND_REMINDER = 5 * 60

REPORT_TIMEOUT = 30 * 60
REPORT_REPEAT_DELAY = 20 * 60
REPORT_FINAL_WAIT = 10 * 60

FASTREQUEST_TIMEOUT = 2 * 60
